"""Bundle the pipeline into one paste-able Kaggle cell.

Used before the repository is on GitHub, when the workflow's code bundle is not
yet available. It packs the real files and runs them as a subprocess -- the same
code path the tests exercise, not a re-implementation, so the bundle cannot
drift into disagreeing with the repo.

Re-run whenever src/ or configs/ changes.

Usage:
    python scripts/build_kaggle_cell.py --entry audit
    python scripts/build_kaggle_cell.py --entry profile
    -> dist/kaggle_<entry>_cell.py
"""

from __future__ import annotations

import argparse
import base64
from pathlib import Path
from typing import Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
KAGGLE_INPUT = "/kaggle/input/cicddos2019-parquet"
DATASET_SLUG = "dungnguyen28101991/cicddos2019-parquet"

ENTRIES = {
    "audit": {
        "script": "src/data_audit.py",
        "title": "step 2: data audit on CIC-DDoS2019",
        "outputs": "/kaggle/working/audit_out/{data_profile,column_mapping,label_mapping}.json",
        "argv": [
            "--dataset", "cicddos2019",
            "--input-root", "{input_root}",
            "--out-dir", "/kaggle/working/audit_out",
            "--repo-root", "{work}",
        ],
        "digest": "/kaggle/working/audit_out/data_profile.json",
        "needs_packages": [],
        "minutes": "a few",
    },
    "profile": {
        "script": "scripts/profile_pipeline.py",
        "title": "step 9: CPU profile and extrapolation",
        "outputs": "/kaggle/working/profile/profile_report.json",
        "argv": [
            "--input-root", "{input_root}",
            "--work-dir", "/kaggle/working/profile",
            "--max-files", "3",
            "--profile-epochs", "3",
        ],
        "digest": None,          # the script prints its own digest
        "needs_packages": ["lightgbm", "shap"],
        "minutes": "20-40",
    },
}


def bundled_files() -> List[Tuple[str, Path]]:
    """Everything the entry point might import: all of src/ and configs/."""
    files: List[Tuple[str, Path]] = []
    for directory in ("src", "configs", "scripts"):
        for path in sorted((REPO_ROOT / directory).rglob("*")):
            if not path.is_file() or "__pycache__" in path.parts:
                continue
            if path.suffix not in (".py", ".yaml"):
                continue
            files.append((path.relative_to(REPO_ROOT).as_posix(), path))
    return files


TEMPLATE = '''\
# ==========================================================================
# CNN-MLP / SHAP / BayesOpt -- {title}
# GENERATED by scripts/build_kaggle_cell.py -- edit the repo, not this file.
#
# Writes: {outputs}
# Runtime: roughly {minutes} minutes.
#
# No AWS credentials, no S3. Reads /kaggle/input, writes /kaggle/working.
# ==========================================================================

import base64, subprocess, sys, textwrap
from pathlib import Path

WORK = Path("/kaggle/working/cnnmlp_code")
INPUT_ROOT = Path({input_root!r})
PACKAGES = {packages!r}

_PAYLOAD = {payload!r}

for rel, blob in _PAYLOAD.items():
    target = WORK / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(base64.b64decode(blob))
print(f"unpacked {{len(_PAYLOAD)}} files into {{WORK}}")

for package in PACKAGES:
    try:
        __import__(package)
    except ImportError:
        print(f"installing {{package}}...")
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", package], check=True)

import torch
print("torch", torch.__version__, "| cuda visible:", torch.cuda.is_available())
assert not torch.cuda.is_available(), "set Accelerator to None: this is a CPU-only experiment"

# Kaggle mounts a dataset under the slug's name part, but that can differ from
# what this bundle was built with, so fall back to whatever is actually mounted.
if not INPUT_ROOT.exists():
    mounted = Path("/kaggle/input")
    candidates = [
        p for p in sorted(mounted.rglob("*"))
        if p.is_dir() and next(p.glob("*.parquet"), None) is not None
    ]
    if not candidates:
        raise SystemExit(
            f"{{INPUT_ROOT}} not found and no parquet under {{mounted}}. "
            "Attach the dataset {dataset_slug!r} via Add Data, then re-run."
        )
    INPUT_ROOT = Path(*candidates[0].parts[:-1]) if len(candidates) > 1 else candidates[0]
    print(f"note: using INPUT_ROOT = {{INPUT_ROOT}}")

shards = sorted(INPUT_ROOT.rglob("*.parquet"))
print(f"{{len(shards)}} parquet shards under {{INPUT_ROOT}}")
if not shards:
    raise SystemExit("no .parquet found; is the attached dataset CSV instead?")

argv = [a.format(input_root=str(INPUT_ROOT), work=str(WORK)) for a in {argv!r}]
result = subprocess.run(
    [sys.executable, str(WORK / {script!r}), *argv],
    capture_output=False, text=True,
)
print(f"\\nexit code: {{result.returncode}}")
'''

DIGEST_TAIL = '''
# Compact digest to paste back. The full artifact stays in /kaggle/working.
import json
digest_path = Path({digest!r})
if digest_path.exists():
    profile = json.loads(digest_path.read_text(encoding="utf-8"))
    unmapped = sorted(
        name for name, stat in profile["columns"].items()
        if stat["missing_ratio"] > 0.0 or stat["dtype"] in ("string", "large_string")
    )
    print("\\n===== PASTE THIS BACK =====")
    print(json.dumps({{
        "total_rows": profile["total_rows"],
        "n_files": profile["n_files"],
        "n_raw_columns": profile["n_raw_columns"],
        "n_numeric_columns": profile["n_numeric_columns"],
        "label_column_raw": profile["label_column_raw"],
        "label_counts_raw": profile["label_counts_raw"],
        "label_counts_binary": profile["label_counts_binary"],
        "unknown_labels": profile["unknown_labels"],
        "column_collisions": profile["column_collisions"],
        "estimated_float32_GiB": round(profile["estimated_float32_bytes"] / 2**30, 3),
        "n_unique_source_ip": profile["n_unique_source_ip"],
        "n_unique_destination_ip": profile["n_unique_destination_ip"],
        "timestamp_range": [profile["timestamp_min"], profile["timestamp_max"]],
        "non_numeric_or_missing_columns": unmapped,
        "per_file": {{
            f["path"]: {{"rows": f["rows"], "labels": f["label_counts"]}}
            for f in profile["files"]
        }},
        "checks": profile["checks"],
    }}, indent=1, ensure_ascii=False))
'''


def build(entry: str) -> Path:
    spec = ENTRIES[entry]
    payload: Dict[str, str] = {
        relative: base64.b64encode(path.read_bytes()).decode("ascii")
        for relative, path in bundled_files()
    }

    cell = TEMPLATE.format(
        title=spec["title"],
        outputs=spec["outputs"],
        minutes=spec["minutes"],
        input_root=KAGGLE_INPUT,
        dataset_slug=DATASET_SLUG,
        packages=spec["needs_packages"],
        payload=payload,
        argv=spec["argv"],
        script=spec["script"],
    )
    if spec["digest"]:
        cell += DIGEST_TAIL.format(digest=spec["digest"])

    out_path = REPO_ROOT / "dist" / f"kaggle_{entry}_cell.py"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(cell, encoding="utf-8")
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--entry", choices=sorted(ENTRIES), default="audit")
    parser.add_argument("--all", action="store_true", help="build every entry point")
    args = parser.parse_args()

    for entry in (sorted(ENTRIES) if args.all else [args.entry]):
        path = build(entry)
        print(f"wrote {path} ({path.stat().st_size / 1024:.0f} KiB, "
              f"{len(bundled_files())} files bundled)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
